import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://10.0.0.64:3000/cellmaUser/login');
  await page.getByTestId('Username').click();
  await page.getByTestId('Username').fill('prerelease.auto');
  await page.getByTestId('Password').click();
  await page.getByTestId('Password').fill('Manoj@2023');
  await page.getByTestId('Login').click();
  await page.getByTestId('Patients').click();
  await page.getByTestId('NHS No').click();
  await page.getByTestId('NHS No').fill('0012');
  await page.getByTestId('Hospital Ref').click();
  await page.getByTestId('Hospital Ref').fill('1254');
  await page.getByTestId('Given Name').click();
  await page.getByTestId('Given Name').fill('Patients');
  await page.getByTestId('Family Name').click();
  await page.getByTestId('Family Name').fill('Searchpt');
  await page.getByTestId('Sex').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByLabel('Choose date').click();
  await page.getByLabel('Mar 12,').click();
  await page.getByTestId('Mobile').click();
  await page.getByTestId('Mobile').fill('9854215487');
  await page.getByTestId('Postcode').click();
  await page.getByTestId('Postcode').fill('411025');
  await page.getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: '1 Day' }).click();
  await page.getByRole('checkbox', { name: 'Include deceased patients' }).check();
  await page.getByRole('checkbox', { name: 'Include service patients' }).check();
  await page.getByRole('checkbox', { name: 'Soundex' }).check();
  await page.getByTestId('Search').click();
  await page.getByTestId('Add Patient').click();
  await page.getByTestId('uniqueIdentification').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Aadhar Card' }).click();
  await page.getByTestId('Unique Identification ID').click();
  await page.getByTestId('Unique Identification ID').fill('985487542154');
  await page.getByTestId('photoIdentification').getByLabel('Open').click();
  await page.getByRole('option', { name: 'PAN Card' }).click();
  await page.getByTestId('Photo Identification ID').click();
  await page.getByTestId('Photo Identification ID').fill('APOTY2887O');
  await page.getByTestId('issuingCountry').getByLabel('Open').click();
  await page.getByTestId('issuingCountry').getByLabel('Issuing Country').fill('ind');
  await page.getByRole('option', { name: 'India', exact: true }).click();
  await page.getByTestId('Title').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'B/O' }).click();
  await page.getByTestId('Middle Name(s)').click();
  await page.getByTestId('Middle Name(s)').fill('Pune');
  await page.getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByTestId('Duplicate Check').click();
  await page.getByTestId('Create Patient').click();
  await page.getByTestId('Marital Status').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.getByTestId('Sexual Orientation').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Heterosexuality' }).click();
  await page.getByTestId('Ethnicity').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Indian' }).click();
  await page.getByTestId('Occupation').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Trainer' }).click();
  await page.getByTestId('Religion').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Hindu' }).click();
  await page.getByTestId('Town Of Birth').click();
  await page.getByTestId('Town Of Birth').fill('Hadapsar');
  await page.getByTestId('County Of Birth').click();
  await page.getByTestId('County Of Birth').fill('Maharashtra');
  await page.getByTestId('Country Of Birth').getByLabel('​', { exact: true }).click();
  await page.locator('#menu-patCountryOfBirth div').first().click();
  await page.getByTestId('Country Of Birth').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'India', exact: true }).click();
  await page.getByTestId('Nationality').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Indian' }).click();
  await page.getByTestId('Primary Disability').getByLabel('​', { exact: true }).click();
  await page.getByRole('checkbox').check();
  await page.locator('#menu-primaryDisability > .MuiBackdrop-root').click();
  await page.getByTestId('Assistance Needed').click();
  await page.getByTestId('Assistance Needed').fill('No');
  await page.getByTestId('Language').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Hindi' }).click();
  await page.getByTestId('Prisoner').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByTestId('Patient Type').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'Regular' }).click();
  await page.getByTestId('Blood Type').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'B+', exact: true }).click();
  await page.getByTestId('Restricted Registration').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByTestId('Patient Web Access').getByLabel('​', { exact: true }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByTestId('Next').click();
  await page.locator('#numberRoadPermanentAddress').click();
  await page.locator('#numberRoadPermanentAddress').fill('Not Kn15own');
  await page.locator('#numberRoadPermanentAddress').click();
  await page.locator('#numberRoadPermanentAddress').press('Tab');
  await page.locator('#townPermanentAddress').click();
  await page.locator('#numberRoadPermanentAddress').click();
  await page.locator('#numberRoadPermanentAddress').fill('15 number');
  await page.locator('#numberRoadPermanentAddress').press('Tab');
  await page.locator('#townPermanentAddress').fill('Hadapsar');
  await page.locator('#townPermanentAddress').press('Tab');
  await page.locator('#districtPermanentAddress').fill('Pune');
  await page.locator('#districtPermanentAddress').press('Tab');
  await page.locator('#countyPermanentAddress').fill('Maharashtra');
  await page.locator('#countyPermanentAddress').press('Tab');
  await page.locator('#postCodePermanentAddress').fill('411028');
  await page.locator('#mui-component-select-country').click();
  await page.locator('#menu-country div').first().click();
  await page.getByTestId('Find Postcode').first().click();
  await page.getByTestId('CommonCellmaPopup').getByTestId('Save').click();
  await page.getByTestId('Find Postcode').first().click();
  await page.getByTestId('CommonCellmaPopup').getByTestId('Country').click();
  await page.getByTestId('CommonCellmaPopup').getByTestId('Country').fill('India');
  await page.getByTestId('CommonCellmaPopup').getByTestId('Save').click();
  await page.getByTestId('Save').click();
});